# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Revan Sopher
tagline:          "A couple decades late to the dotcom bubble?"
description:      "The dusty remains of a web presence."
url:              http://revan.io

author:
  name:           'Revan Sopher'

paginate_path:    "blog/page:num"
paginate:         5

resume:           'https://www.dropbox.com/s/rdg3im8c4iij8j0/resumerevan.pdf?raw=1'
